// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: input_event.proto

#ifndef PROTOBUF_INCLUDED_input_5fevent_2eproto
#define PROTOBUF_INCLUDED_input_5fevent_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_input_5fevent_2eproto 

namespace protobuf_input_5fevent_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_input_5fevent_2eproto
class InputEventRequest;
class InputEventRequestDefaultTypeInternal;
extern InputEventRequestDefaultTypeInternal _InputEventRequest_default_instance_;
class InputEventResponse;
class InputEventResponseDefaultTypeInternal;
extern InputEventResponseDefaultTypeInternal _InputEventResponse_default_instance_;
namespace google {
namespace protobuf {
template<> ::InputEventRequest* Arena::CreateMaybeMessage<::InputEventRequest>(Arena*);
template<> ::InputEventResponse* Arena::CreateMaybeMessage<::InputEventResponse>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class InputEventRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:InputEventRequest) */ {
 public:
  InputEventRequest();
  virtual ~InputEventRequest();

  InputEventRequest(const InputEventRequest& from);

  inline InputEventRequest& operator=(const InputEventRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InputEventRequest(InputEventRequest&& from) noexcept
    : InputEventRequest() {
    *this = ::std::move(from);
  }

  inline InputEventRequest& operator=(InputEventRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const InputEventRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InputEventRequest* internal_default_instance() {
    return reinterpret_cast<const InputEventRequest*>(
               &_InputEventRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(InputEventRequest* other);
  friend void swap(InputEventRequest& a, InputEventRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InputEventRequest* New() const final {
    return CreateMaybeMessage<InputEventRequest>(NULL);
  }

  InputEventRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InputEventRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InputEventRequest& from);
  void MergeFrom(const InputEventRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InputEventRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 serial = 1;
  void clear_serial();
  static const int kSerialFieldNumber = 1;
  ::google::protobuf::int64 serial() const;
  void set_serial(::google::protobuf::int64 value);

  // int32 type = 2;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // int32 code = 3;
  void clear_code();
  static const int kCodeFieldNumber = 3;
  ::google::protobuf::int32 code() const;
  void set_code(::google::protobuf::int32 value);

  // int32 value = 4;
  void clear_value();
  static const int kValueFieldNumber = 4;
  ::google::protobuf::int32 value() const;
  void set_value(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:InputEventRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 serial_;
  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 code_;
  ::google::protobuf::int32 value_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_input_5fevent_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class InputEventResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:InputEventResponse) */ {
 public:
  InputEventResponse();
  virtual ~InputEventResponse();

  InputEventResponse(const InputEventResponse& from);

  inline InputEventResponse& operator=(const InputEventResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InputEventResponse(InputEventResponse&& from) noexcept
    : InputEventResponse() {
    *this = ::std::move(from);
  }

  inline InputEventResponse& operator=(InputEventResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const InputEventResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InputEventResponse* internal_default_instance() {
    return reinterpret_cast<const InputEventResponse*>(
               &_InputEventResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(InputEventResponse* other);
  friend void swap(InputEventResponse& a, InputEventResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InputEventResponse* New() const final {
    return CreateMaybeMessage<InputEventResponse>(NULL);
  }

  InputEventResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InputEventResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InputEventResponse& from);
  void MergeFrom(const InputEventResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InputEventResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 serial = 1;
  void clear_serial();
  static const int kSerialFieldNumber = 1;
  ::google::protobuf::int64 serial() const;
  void set_serial(::google::protobuf::int64 value);

  // bool success = 2;
  void clear_success();
  static const int kSuccessFieldNumber = 2;
  bool success() const;
  void set_success(bool value);

  // @@protoc_insertion_point(class_scope:InputEventResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 serial_;
  bool success_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_input_5fevent_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// InputEventRequest

// int64 serial = 1;
inline void InputEventRequest::clear_serial() {
  serial_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 InputEventRequest::serial() const {
  // @@protoc_insertion_point(field_get:InputEventRequest.serial)
  return serial_;
}
inline void InputEventRequest::set_serial(::google::protobuf::int64 value) {
  
  serial_ = value;
  // @@protoc_insertion_point(field_set:InputEventRequest.serial)
}

// int32 type = 2;
inline void InputEventRequest::clear_type() {
  type_ = 0;
}
inline ::google::protobuf::int32 InputEventRequest::type() const {
  // @@protoc_insertion_point(field_get:InputEventRequest.type)
  return type_;
}
inline void InputEventRequest::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:InputEventRequest.type)
}

// int32 code = 3;
inline void InputEventRequest::clear_code() {
  code_ = 0;
}
inline ::google::protobuf::int32 InputEventRequest::code() const {
  // @@protoc_insertion_point(field_get:InputEventRequest.code)
  return code_;
}
inline void InputEventRequest::set_code(::google::protobuf::int32 value) {
  
  code_ = value;
  // @@protoc_insertion_point(field_set:InputEventRequest.code)
}

// int32 value = 4;
inline void InputEventRequest::clear_value() {
  value_ = 0;
}
inline ::google::protobuf::int32 InputEventRequest::value() const {
  // @@protoc_insertion_point(field_get:InputEventRequest.value)
  return value_;
}
inline void InputEventRequest::set_value(::google::protobuf::int32 value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:InputEventRequest.value)
}

// -------------------------------------------------------------------

// InputEventResponse

// int64 serial = 1;
inline void InputEventResponse::clear_serial() {
  serial_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 InputEventResponse::serial() const {
  // @@protoc_insertion_point(field_get:InputEventResponse.serial)
  return serial_;
}
inline void InputEventResponse::set_serial(::google::protobuf::int64 value) {
  
  serial_ = value;
  // @@protoc_insertion_point(field_set:InputEventResponse.serial)
}

// bool success = 2;
inline void InputEventResponse::clear_success() {
  success_ = false;
}
inline bool InputEventResponse::success() const {
  // @@protoc_insertion_point(field_get:InputEventResponse.success)
  return success_;
}
inline void InputEventResponse::set_success(bool value) {
  
  success_ = value;
  // @@protoc_insertion_point(field_set:InputEventResponse.success)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_input_5fevent_2eproto
