// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pair.proto

#include "pair.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

class ScanRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ScanRequest>
      _instance;
} _ScanRequest_default_instance_;
class ScanResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ScanResponse>
      _instance;
} _ScanResponse_default_instance_;
class PairRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PairRequest>
      _instance;
} _PairRequest_default_instance_;
class PairResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PairResponse>
      _instance;
} _PairResponse_default_instance_;
class StopPairRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<StopPairRequest>
      _instance;
} _StopPairRequest_default_instance_;
class StopPairResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<StopPairResponse>
      _instance;
} _StopPairResponse_default_instance_;
namespace protobuf_pair_2eproto {
static void InitDefaultsScanRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_ScanRequest_default_instance_;
    new (ptr) ::ScanRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ScanRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ScanRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsScanRequest}, {}};

static void InitDefaultsScanResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_ScanResponse_default_instance_;
    new (ptr) ::ScanResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ScanResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ScanResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsScanResponse}, {}};

static void InitDefaultsPairRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_PairRequest_default_instance_;
    new (ptr) ::PairRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PairRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PairRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPairRequest}, {}};

static void InitDefaultsPairResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_PairResponse_default_instance_;
    new (ptr) ::PairResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PairResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PairResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPairResponse}, {}};

static void InitDefaultsStopPairRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_StopPairRequest_default_instance_;
    new (ptr) ::StopPairRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::StopPairRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_StopPairRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsStopPairRequest}, {}};

static void InitDefaultsStopPairResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_StopPairResponse_default_instance_;
    new (ptr) ::StopPairResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::StopPairResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_StopPairResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsStopPairResponse}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ScanRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ScanResponse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PairRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PairResponse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_StopPairRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_StopPairResponse.base);
}

::google::protobuf::Metadata file_level_metadata[6];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ScanRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ScanRequest, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ScanRequest, master_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ScanRequest, os_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ScanResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ScanResponse, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ScanResponse, slave_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ScanResponse, os_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ScanResponse, port_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PairRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PairRequest, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PairRequest, master_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PairRequest, os_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PairResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PairResponse, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PairResponse, slave_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PairResponse, os_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PairResponse, agree_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::StopPairRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::StopPairRequest, immediately_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::StopPairResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::StopPairResponse, bye_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ScanRequest)},
  { 8, -1, sizeof(::ScanResponse)},
  { 17, -1, sizeof(::PairRequest)},
  { 25, -1, sizeof(::PairResponse)},
  { 34, -1, sizeof(::StopPairRequest)},
  { 40, -1, sizeof(::StopPairResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_ScanRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_ScanResponse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_PairRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_PairResponse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_StopPairRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_StopPairResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "pair.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 6);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\npair.proto\"F\n\013ScanRequest\022\013\n\003key\030\001 \001(\t"
      "\022\023\n\013master_name\030\002 \001(\t\022\025\n\002os\030\003 \001(\0162\t.Devi"
      "ceOS\"T\n\014ScanResponse\022\013\n\003key\030\001 \001(\t\022\022\n\nsla"
      "ve_name\030\002 \001(\t\022\025\n\002os\030\003 \001(\0162\t.DeviceOS\022\014\n\004"
      "port\030\004 \001(\005\"F\n\013PairRequest\022\013\n\003key\030\001 \001(\t\022\023"
      "\n\013master_name\030\002 \001(\t\022\025\n\002os\030\003 \001(\0162\t.Device"
      "OS\"U\n\014PairResponse\022\013\n\003key\030\001 \001(\t\022\022\n\nslave"
      "_name\030\002 \001(\t\022\025\n\002os\030\003 \001(\0162\t.DeviceOS\022\r\n\005ag"
      "ree\030\004 \001(\010\"&\n\017StopPairRequest\022\023\n\013immediat"
      "ely\030\001 \001(\010\"\037\n\020StopPairResponse\022\013\n\003bye\030\001 \001"
      "(\t*N\n\010DeviceOS\022\t\n\005OTHER\020\000\022\007\n\003UOS\020\001\022\t\n\005LI"
      "NUX\020\002\022\013\n\007WINDOWS\020\003\022\t\n\005MACOS\020\004\022\013\n\007ANDROID"
      "\020\005b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 490);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "pair.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_pair_2eproto
const ::google::protobuf::EnumDescriptor* DeviceOS_descriptor() {
  protobuf_pair_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_pair_2eproto::file_level_enum_descriptors[0];
}
bool DeviceOS_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void ScanRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ScanRequest::kKeyFieldNumber;
const int ScanRequest::kMasterNameFieldNumber;
const int ScanRequest::kOsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ScanRequest::ScanRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_pair_2eproto::scc_info_ScanRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ScanRequest)
}
ScanRequest::ScanRequest(const ScanRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.key().size() > 0) {
    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  master_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.master_name().size() > 0) {
    master_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.master_name_);
  }
  os_ = from.os_;
  // @@protoc_insertion_point(copy_constructor:ScanRequest)
}

void ScanRequest::SharedCtor() {
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  master_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  os_ = 0;
}

ScanRequest::~ScanRequest() {
  // @@protoc_insertion_point(destructor:ScanRequest)
  SharedDtor();
}

void ScanRequest::SharedDtor() {
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  master_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ScanRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ScanRequest::descriptor() {
  ::protobuf_pair_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_pair_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ScanRequest& ScanRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_pair_2eproto::scc_info_ScanRequest.base);
  return *internal_default_instance();
}


void ScanRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ScanRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  master_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  os_ = 0;
  _internal_metadata_.Clear();
}

bool ScanRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ScanRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string key = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->key().data(), static_cast<int>(this->key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ScanRequest.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string master_name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_master_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->master_name().data(), static_cast<int>(this->master_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ScanRequest.master_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .DeviceOS os = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_os(static_cast< ::DeviceOS >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ScanRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ScanRequest)
  return false;
#undef DO_
}

void ScanRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ScanRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ScanRequest.key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->key(), output);
  }

  // string master_name = 2;
  if (this->master_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->master_name().data(), static_cast<int>(this->master_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ScanRequest.master_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->master_name(), output);
  }

  // .DeviceOS os = 3;
  if (this->os() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->os(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ScanRequest)
}

::google::protobuf::uint8* ScanRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ScanRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ScanRequest.key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->key(), target);
  }

  // string master_name = 2;
  if (this->master_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->master_name().data(), static_cast<int>(this->master_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ScanRequest.master_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->master_name(), target);
  }

  // .DeviceOS os = 3;
  if (this->os() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->os(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ScanRequest)
  return target;
}

size_t ScanRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ScanRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string key = 1;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->key());
  }

  // string master_name = 2;
  if (this->master_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->master_name());
  }

  // .DeviceOS os = 3;
  if (this->os() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->os());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ScanRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ScanRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const ScanRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ScanRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ScanRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ScanRequest)
    MergeFrom(*source);
  }
}

void ScanRequest::MergeFrom(const ScanRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ScanRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  if (from.master_name().size() > 0) {

    master_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.master_name_);
  }
  if (from.os() != 0) {
    set_os(from.os());
  }
}

void ScanRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ScanRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ScanRequest::CopyFrom(const ScanRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ScanRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ScanRequest::IsInitialized() const {
  return true;
}

void ScanRequest::Swap(ScanRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ScanRequest::InternalSwap(ScanRequest* other) {
  using std::swap;
  key_.Swap(&other->key_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  master_name_.Swap(&other->master_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(os_, other->os_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ScanRequest::GetMetadata() const {
  protobuf_pair_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_pair_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ScanResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ScanResponse::kKeyFieldNumber;
const int ScanResponse::kSlaveNameFieldNumber;
const int ScanResponse::kOsFieldNumber;
const int ScanResponse::kPortFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ScanResponse::ScanResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_pair_2eproto::scc_info_ScanResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ScanResponse)
}
ScanResponse::ScanResponse(const ScanResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.key().size() > 0) {
    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  slave_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.slave_name().size() > 0) {
    slave_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.slave_name_);
  }
  ::memcpy(&os_, &from.os_,
    static_cast<size_t>(reinterpret_cast<char*>(&port_) -
    reinterpret_cast<char*>(&os_)) + sizeof(port_));
  // @@protoc_insertion_point(copy_constructor:ScanResponse)
}

void ScanResponse::SharedCtor() {
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  slave_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&os_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&port_) -
      reinterpret_cast<char*>(&os_)) + sizeof(port_));
}

ScanResponse::~ScanResponse() {
  // @@protoc_insertion_point(destructor:ScanResponse)
  SharedDtor();
}

void ScanResponse::SharedDtor() {
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  slave_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ScanResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ScanResponse::descriptor() {
  ::protobuf_pair_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_pair_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ScanResponse& ScanResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_pair_2eproto::scc_info_ScanResponse.base);
  return *internal_default_instance();
}


void ScanResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:ScanResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  slave_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&os_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&port_) -
      reinterpret_cast<char*>(&os_)) + sizeof(port_));
  _internal_metadata_.Clear();
}

bool ScanResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ScanResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string key = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->key().data(), static_cast<int>(this->key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ScanResponse.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string slave_name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_slave_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->slave_name().data(), static_cast<int>(this->slave_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ScanResponse.slave_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .DeviceOS os = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_os(static_cast< ::DeviceOS >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 port = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &port_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ScanResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ScanResponse)
  return false;
#undef DO_
}

void ScanResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ScanResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ScanResponse.key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->key(), output);
  }

  // string slave_name = 2;
  if (this->slave_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->slave_name().data(), static_cast<int>(this->slave_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ScanResponse.slave_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->slave_name(), output);
  }

  // .DeviceOS os = 3;
  if (this->os() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->os(), output);
  }

  // int32 port = 4;
  if (this->port() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->port(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ScanResponse)
}

::google::protobuf::uint8* ScanResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ScanResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ScanResponse.key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->key(), target);
  }

  // string slave_name = 2;
  if (this->slave_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->slave_name().data(), static_cast<int>(this->slave_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ScanResponse.slave_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->slave_name(), target);
  }

  // .DeviceOS os = 3;
  if (this->os() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->os(), target);
  }

  // int32 port = 4;
  if (this->port() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->port(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ScanResponse)
  return target;
}

size_t ScanResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ScanResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string key = 1;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->key());
  }

  // string slave_name = 2;
  if (this->slave_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->slave_name());
  }

  // .DeviceOS os = 3;
  if (this->os() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->os());
  }

  // int32 port = 4;
  if (this->port() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->port());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ScanResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ScanResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const ScanResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ScanResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ScanResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ScanResponse)
    MergeFrom(*source);
  }
}

void ScanResponse::MergeFrom(const ScanResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ScanResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  if (from.slave_name().size() > 0) {

    slave_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.slave_name_);
  }
  if (from.os() != 0) {
    set_os(from.os());
  }
  if (from.port() != 0) {
    set_port(from.port());
  }
}

void ScanResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ScanResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ScanResponse::CopyFrom(const ScanResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ScanResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ScanResponse::IsInitialized() const {
  return true;
}

void ScanResponse::Swap(ScanResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ScanResponse::InternalSwap(ScanResponse* other) {
  using std::swap;
  key_.Swap(&other->key_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  slave_name_.Swap(&other->slave_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(os_, other->os_);
  swap(port_, other->port_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ScanResponse::GetMetadata() const {
  protobuf_pair_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_pair_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PairRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PairRequest::kKeyFieldNumber;
const int PairRequest::kMasterNameFieldNumber;
const int PairRequest::kOsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PairRequest::PairRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_pair_2eproto::scc_info_PairRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:PairRequest)
}
PairRequest::PairRequest(const PairRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.key().size() > 0) {
    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  master_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.master_name().size() > 0) {
    master_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.master_name_);
  }
  os_ = from.os_;
  // @@protoc_insertion_point(copy_constructor:PairRequest)
}

void PairRequest::SharedCtor() {
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  master_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  os_ = 0;
}

PairRequest::~PairRequest() {
  // @@protoc_insertion_point(destructor:PairRequest)
  SharedDtor();
}

void PairRequest::SharedDtor() {
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  master_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void PairRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PairRequest::descriptor() {
  ::protobuf_pair_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_pair_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PairRequest& PairRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_pair_2eproto::scc_info_PairRequest.base);
  return *internal_default_instance();
}


void PairRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:PairRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  master_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  os_ = 0;
  _internal_metadata_.Clear();
}

bool PairRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PairRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string key = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->key().data(), static_cast<int>(this->key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "PairRequest.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string master_name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_master_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->master_name().data(), static_cast<int>(this->master_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "PairRequest.master_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .DeviceOS os = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_os(static_cast< ::DeviceOS >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PairRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PairRequest)
  return false;
#undef DO_
}

void PairRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PairRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PairRequest.key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->key(), output);
  }

  // string master_name = 2;
  if (this->master_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->master_name().data(), static_cast<int>(this->master_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PairRequest.master_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->master_name(), output);
  }

  // .DeviceOS os = 3;
  if (this->os() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->os(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:PairRequest)
}

::google::protobuf::uint8* PairRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:PairRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PairRequest.key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->key(), target);
  }

  // string master_name = 2;
  if (this->master_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->master_name().data(), static_cast<int>(this->master_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PairRequest.master_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->master_name(), target);
  }

  // .DeviceOS os = 3;
  if (this->os() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->os(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PairRequest)
  return target;
}

size_t PairRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PairRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string key = 1;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->key());
  }

  // string master_name = 2;
  if (this->master_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->master_name());
  }

  // .DeviceOS os = 3;
  if (this->os() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->os());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PairRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PairRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const PairRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PairRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PairRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PairRequest)
    MergeFrom(*source);
  }
}

void PairRequest::MergeFrom(const PairRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PairRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  if (from.master_name().size() > 0) {

    master_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.master_name_);
  }
  if (from.os() != 0) {
    set_os(from.os());
  }
}

void PairRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PairRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PairRequest::CopyFrom(const PairRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PairRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PairRequest::IsInitialized() const {
  return true;
}

void PairRequest::Swap(PairRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PairRequest::InternalSwap(PairRequest* other) {
  using std::swap;
  key_.Swap(&other->key_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  master_name_.Swap(&other->master_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(os_, other->os_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PairRequest::GetMetadata() const {
  protobuf_pair_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_pair_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PairResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PairResponse::kKeyFieldNumber;
const int PairResponse::kSlaveNameFieldNumber;
const int PairResponse::kOsFieldNumber;
const int PairResponse::kAgreeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PairResponse::PairResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_pair_2eproto::scc_info_PairResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:PairResponse)
}
PairResponse::PairResponse(const PairResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.key().size() > 0) {
    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  slave_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.slave_name().size() > 0) {
    slave_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.slave_name_);
  }
  ::memcpy(&os_, &from.os_,
    static_cast<size_t>(reinterpret_cast<char*>(&agree_) -
    reinterpret_cast<char*>(&os_)) + sizeof(agree_));
  // @@protoc_insertion_point(copy_constructor:PairResponse)
}

void PairResponse::SharedCtor() {
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  slave_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&os_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&agree_) -
      reinterpret_cast<char*>(&os_)) + sizeof(agree_));
}

PairResponse::~PairResponse() {
  // @@protoc_insertion_point(destructor:PairResponse)
  SharedDtor();
}

void PairResponse::SharedDtor() {
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  slave_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void PairResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PairResponse::descriptor() {
  ::protobuf_pair_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_pair_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PairResponse& PairResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_pair_2eproto::scc_info_PairResponse.base);
  return *internal_default_instance();
}


void PairResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:PairResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  slave_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&os_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&agree_) -
      reinterpret_cast<char*>(&os_)) + sizeof(agree_));
  _internal_metadata_.Clear();
}

bool PairResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PairResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string key = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->key().data(), static_cast<int>(this->key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "PairResponse.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string slave_name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_slave_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->slave_name().data(), static_cast<int>(this->slave_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "PairResponse.slave_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .DeviceOS os = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_os(static_cast< ::DeviceOS >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool agree = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &agree_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PairResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PairResponse)
  return false;
#undef DO_
}

void PairResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PairResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PairResponse.key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->key(), output);
  }

  // string slave_name = 2;
  if (this->slave_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->slave_name().data(), static_cast<int>(this->slave_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PairResponse.slave_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->slave_name(), output);
  }

  // .DeviceOS os = 3;
  if (this->os() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->os(), output);
  }

  // bool agree = 4;
  if (this->agree() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->agree(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:PairResponse)
}

::google::protobuf::uint8* PairResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:PairResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), static_cast<int>(this->key().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PairResponse.key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->key(), target);
  }

  // string slave_name = 2;
  if (this->slave_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->slave_name().data(), static_cast<int>(this->slave_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PairResponse.slave_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->slave_name(), target);
  }

  // .DeviceOS os = 3;
  if (this->os() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->os(), target);
  }

  // bool agree = 4;
  if (this->agree() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->agree(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PairResponse)
  return target;
}

size_t PairResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PairResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string key = 1;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->key());
  }

  // string slave_name = 2;
  if (this->slave_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->slave_name());
  }

  // .DeviceOS os = 3;
  if (this->os() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->os());
  }

  // bool agree = 4;
  if (this->agree() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PairResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PairResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const PairResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PairResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PairResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PairResponse)
    MergeFrom(*source);
  }
}

void PairResponse::MergeFrom(const PairResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PairResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  if (from.slave_name().size() > 0) {

    slave_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.slave_name_);
  }
  if (from.os() != 0) {
    set_os(from.os());
  }
  if (from.agree() != 0) {
    set_agree(from.agree());
  }
}

void PairResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PairResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PairResponse::CopyFrom(const PairResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PairResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PairResponse::IsInitialized() const {
  return true;
}

void PairResponse::Swap(PairResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PairResponse::InternalSwap(PairResponse* other) {
  using std::swap;
  key_.Swap(&other->key_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  slave_name_.Swap(&other->slave_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(os_, other->os_);
  swap(agree_, other->agree_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PairResponse::GetMetadata() const {
  protobuf_pair_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_pair_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void StopPairRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StopPairRequest::kImmediatelyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StopPairRequest::StopPairRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_pair_2eproto::scc_info_StopPairRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:StopPairRequest)
}
StopPairRequest::StopPairRequest(const StopPairRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  immediately_ = from.immediately_;
  // @@protoc_insertion_point(copy_constructor:StopPairRequest)
}

void StopPairRequest::SharedCtor() {
  immediately_ = false;
}

StopPairRequest::~StopPairRequest() {
  // @@protoc_insertion_point(destructor:StopPairRequest)
  SharedDtor();
}

void StopPairRequest::SharedDtor() {
}

void StopPairRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* StopPairRequest::descriptor() {
  ::protobuf_pair_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_pair_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const StopPairRequest& StopPairRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_pair_2eproto::scc_info_StopPairRequest.base);
  return *internal_default_instance();
}


void StopPairRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:StopPairRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  immediately_ = false;
  _internal_metadata_.Clear();
}

bool StopPairRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:StopPairRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool immediately = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &immediately_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:StopPairRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:StopPairRequest)
  return false;
#undef DO_
}

void StopPairRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:StopPairRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool immediately = 1;
  if (this->immediately() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->immediately(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:StopPairRequest)
}

::google::protobuf::uint8* StopPairRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:StopPairRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool immediately = 1;
  if (this->immediately() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->immediately(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:StopPairRequest)
  return target;
}

size_t StopPairRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:StopPairRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bool immediately = 1;
  if (this->immediately() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void StopPairRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:StopPairRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const StopPairRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const StopPairRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:StopPairRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:StopPairRequest)
    MergeFrom(*source);
  }
}

void StopPairRequest::MergeFrom(const StopPairRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:StopPairRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.immediately() != 0) {
    set_immediately(from.immediately());
  }
}

void StopPairRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:StopPairRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StopPairRequest::CopyFrom(const StopPairRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:StopPairRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StopPairRequest::IsInitialized() const {
  return true;
}

void StopPairRequest::Swap(StopPairRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StopPairRequest::InternalSwap(StopPairRequest* other) {
  using std::swap;
  swap(immediately_, other->immediately_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata StopPairRequest::GetMetadata() const {
  protobuf_pair_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_pair_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void StopPairResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StopPairResponse::kByeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StopPairResponse::StopPairResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_pair_2eproto::scc_info_StopPairResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:StopPairResponse)
}
StopPairResponse::StopPairResponse(const StopPairResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  bye_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.bye().size() > 0) {
    bye_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bye_);
  }
  // @@protoc_insertion_point(copy_constructor:StopPairResponse)
}

void StopPairResponse::SharedCtor() {
  bye_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

StopPairResponse::~StopPairResponse() {
  // @@protoc_insertion_point(destructor:StopPairResponse)
  SharedDtor();
}

void StopPairResponse::SharedDtor() {
  bye_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void StopPairResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* StopPairResponse::descriptor() {
  ::protobuf_pair_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_pair_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const StopPairResponse& StopPairResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_pair_2eproto::scc_info_StopPairResponse.base);
  return *internal_default_instance();
}


void StopPairResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:StopPairResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  bye_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool StopPairResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:StopPairResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string bye = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_bye()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->bye().data(), static_cast<int>(this->bye().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "StopPairResponse.bye"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:StopPairResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:StopPairResponse)
  return false;
#undef DO_
}

void StopPairResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:StopPairResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string bye = 1;
  if (this->bye().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->bye().data(), static_cast<int>(this->bye().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "StopPairResponse.bye");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->bye(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:StopPairResponse)
}

::google::protobuf::uint8* StopPairResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:StopPairResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string bye = 1;
  if (this->bye().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->bye().data(), static_cast<int>(this->bye().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "StopPairResponse.bye");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->bye(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:StopPairResponse)
  return target;
}

size_t StopPairResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:StopPairResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string bye = 1;
  if (this->bye().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->bye());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void StopPairResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:StopPairResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const StopPairResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const StopPairResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:StopPairResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:StopPairResponse)
    MergeFrom(*source);
  }
}

void StopPairResponse::MergeFrom(const StopPairResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:StopPairResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.bye().size() > 0) {

    bye_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bye_);
  }
}

void StopPairResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:StopPairResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StopPairResponse::CopyFrom(const StopPairResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:StopPairResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StopPairResponse::IsInitialized() const {
  return true;
}

void StopPairResponse::Swap(StopPairResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StopPairResponse::InternalSwap(StopPairResponse* other) {
  using std::swap;
  bye_.Swap(&other->bye_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata StopPairResponse::GetMetadata() const {
  protobuf_pair_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_pair_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ScanRequest* Arena::CreateMaybeMessage< ::ScanRequest >(Arena* arena) {
  return Arena::CreateInternal< ::ScanRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ScanResponse* Arena::CreateMaybeMessage< ::ScanResponse >(Arena* arena) {
  return Arena::CreateInternal< ::ScanResponse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::PairRequest* Arena::CreateMaybeMessage< ::PairRequest >(Arena* arena) {
  return Arena::CreateInternal< ::PairRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::PairResponse* Arena::CreateMaybeMessage< ::PairResponse >(Arena* arena) {
  return Arena::CreateInternal< ::PairResponse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::StopPairRequest* Arena::CreateMaybeMessage< ::StopPairRequest >(Arena* arena) {
  return Arena::CreateInternal< ::StopPairRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::StopPairResponse* Arena::CreateMaybeMessage< ::StopPairResponse >(Arena* arena) {
  return Arena::CreateInternal< ::StopPairResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
